### ISSUE TITLE
安装deluge 1.3.15 出现问题

### ISSUE THREAD

**Issue by kakolukia** [Aniverse/inexistence#24]
感谢星大奉献，rt+rut+autodl-irssi没问题，其他没试，不过deluge启动不了
ubuntu 16.04，不管是安装官方版还是skip hashcheck的都同样无法启动

> root@ubuntu:~# deluged
root@ubuntu:~# [ERROR   ] 23:39:59 main:248 No module named libtorrent
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.15-py2.7.egg/deluge/main.py", line 241, in start_daemon
    Daemon(options, args)
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.15-py2.7.egg/deluge/core/daemon.py", line 144, in __init__
    from deluge.core.core import Core
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.15-py2.7.egg/deluge/core/core.py", line 38, in <module>
    from deluge._libtorrent import lt
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.15-py2.7.egg/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: No module named libtorrent

**Comment by Aniverse** [comment]
libtorrent 版本选的什么，qb 版本选的什么？

**Comment by c939984606** [comment]
我的ubuntu16.04没问题，我在op三个机器和本地机器都测过，而且现在正在用。

**Comment by Aniverse** [comment]
256MB 内存的 OpenVZ 小鸡，无法开启 swap，内存太小不足以编译 libtorrent-rasterbar，编译时出错，故 deluged 找不到 libtorrent
